# Generated by Django 2.0.5 on 2018-10-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='goals',
            field=models.TextField(default=''),
        ),
    ]
