# Generated by Django 2.0.5 on 2018-10-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181028_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='file',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
